--- 
title: "Automated Gating of Flow Cytometry Data using the Bioconductor `openCyto` Framework"
author: 
- "Nichole Monhait, MPH Candidate"
- "Colorado School of Public Health, Colorado State University"    
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
#bibliography: [book.bib, packages.bib]
#biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This tutorial was created to allow users to automate flow cytometry analysis in R using the `openCyto` package. The tutorial includes steps to complete automation from a flowJo Workspace file. Full details on tutorial contents are included in the following chapters."
---

# What's inside?  

Flow cyometry is a method used to gain understanding of cell samples and populations by quantifying scattered and emitted fluorescent light. Signals are captured and analyzed through use of software programs. Flow cytometry analysis consists of gating, a method that dictates which cells will be further analyzed and which will not. Current methods for flow cytometry gating involve manually drawing gates. This process is both time consuming and costly, making automated gating procedures an appealing option. The `openCyto` package allows users to take manually gated data from flowJo, reproduce those gates in R, and eventually automate the gating process. The goal of this tutorial is to take the user through the process of automated gating analysis.  

This tutorial will be useful to anyone who has done manual gating on a sample and wishes to automate the same procedure on additional samples in the future. 

The example data used in this tutorial is from Colorado State University's Microbiology, Immunology, and Pathology Department. Alternatively, you can input your own data using the filetypes described in Chapter 3.  


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
